
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def problem(limit):
	fib_a = 1
	fib_b = 2
	answer = 2
	while fib_b < limit:
		temp = fib_a + fib_b
		if temp % 2 == 0:
			answer += temp
		fib_a = fib_b
		fib_b = temp
	return answer


if __name__ == '__main__':
	print(problem(4000000))